### PR TITLE
fix: configurable number of worker threads

### LINKED ISSUE #10: Configurable number of worker threads

### PR DESCRIPTION
**Pull request by marcusspangenberg**

### CODE REVIEW

File: entrypoint.sh [hunk 1]
```diff
@@ -25,7 +26,8 @@ cat > config.json << EOF
   "rctl.enable": true,
   "rctl.debugLog": false,
   "mixerInactivityTimeoutMs": ${INACTIVITY_TIMEOUT},
-  "recording.singlePort": 0
+  "recording.singlePort": 0,
+  "numWorkerTreads": ${WORKER_THREADS}
```
Comment (marcusspangenberg) [inline entrypoint.sh:30]: Misspelled intentionally

**Review by birme — APPROVED** [review]
